### ISSUE TITLE
Crashes on login

### ISSUE THREAD

**Issue by alinnow** [automat-berlin/afone#7]
## Steps to reproduce
- Fill in basic login details for provider ([their documentation](https://www.voipfone.co.uk/General_Phone_Setup.php))
- Click login
- Briefly see spinner above login
- App closes

## Setup
iPhone SE (**2nd Generation**)
iOS 14.2

## Notes
Someone else reported the same issue on iPhone SE (1st Generation) in a review on the German App Store.  
I have verified the login credentials in another app

**Comment by rbugajewski** [comment]
This is related to #6

**Comment by alinnow** [comment]
How can the two issues be related? #6 is a layout issue on a smaller display, this is a crash that occurs on **both** iterations of the iPhone SE (i.e. including the one that is essentially an updated iPhone 8; it has a 4.7" display and should not run into any "small display" problems)

I updated the issue, hopefully that makes it clearer

**Comment by shadzik** [comment]
@alanpearce thanks for the input, we will try to reproduce the problem. Could you confirm that it also happens in the iOS Simulator or have you only been testing the App Store version on an iPhone SE device?

**Comment by alinnow** [comment]
I've only been testing the App Store version on a real iPhone SE. I've never used Xcode or the iOS Simulator.

Out of curiosity, I tried the app on an M1 Mac and it is able to connect to the same provider without crashing, so that would suggest it's not necessarily related to the provider.

**Comment by shadzik** [comment]
Thanks for the update. Mac support is totally untested and pure luck it even logs you in :)  I'll have a look and will try to reproduce on the iPhone SE Simulator, unfortunately i can't test it on a real iPhone SE device.

**Comment by shadzik** [comment]
<img width="559" alt="Screenshot 2021-01-07 at 01 30 02" src="https://user-images.githubusercontent.com/2404568/103835978-fc61b180-5087-11eb-944a-fdac81eff904.png">

@alanpearce unfortunately it seems to work on iPhone SE Simulator. Are you able to test it on another device to see if it's related to your SIP provider? Alternatively could you provide test credentials I could use?

**Comment by alinnow** [comment]
I curiously managed to work around it by accident.

I entered my credentials incorrectly and got a local network access request, which I accepted. The login process appeared to hang in the background. When I went back and fixed the credentials, I was able to login and place a call.

**Comment by dsmic** [comment]
I do have the same issue on an iPad Air 2020, with ios 14.4 on a telekom line.

On the own wlan with leaving password empty. (works on my iPad 5th)
